import { ObjectId } from 'mongodb';

/**
 * Represents a todo item in the system
 */
export interface TodoItem {
    _id: ObjectId;
    userId: ObjectId;
    title: string;
    completed: boolean;
    createdAt: Date;
    updatedAt: Date;
}

/**
 * Type for creating a new todo item
 * Omits the _id field which is generated by MongoDB
 */
export type TodoItemCreate = Omit<TodoItem, '_id'>;

/**
 * Type for updating a todo item
 * All fields are optional except updatedAt
 */
export type TodoItemUpdate = Partial<Omit<TodoItem, '_id' | 'userId'>> & {
    updatedAt: Date;
};

/**
 * Client-friendly todo item with string IDs
 */
export interface TodoItemClient {
    _id: string;
    userId: string;
    title: string;
    completed: boolean;
    createdAt: string;
    updatedAt: string;
} 