import { ObjectId } from 'mongodb';

/**
 * How the plan was created
 */
export type PlanCreationSource = 
    | 'manual'      // Created manually via "New Plan" button
    | 'ai'          // Generated by AI from text description
    | 'import'      // Imported from JSON file
    | 'share'       // Added from a shared link
    | 'duplicate';  // Duplicated from another plan

/**
 * Represents a training plan in the system
 */
export interface TrainingPlan {
    _id: ObjectId | string;
    userId: ObjectId | string;
    name: string;
    durationWeeks: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    /** Timestamp of last plan data sync (exercises + progress) */
    lastDataSyncedAt?: number;
    /** How the plan was created (manual, ai, import, share, duplicate) */
    creationSource?: PlanCreationSource;
}

/**
 * Type for creating a new training plan
 */
export type TrainingPlanCreate = Omit<TrainingPlan, '_id'> & { _id?: ObjectId | string };

/**
 * Type for updating a training plan
 */
export type TrainingPlanUpdate = Partial<Omit<TrainingPlan, '_id' | 'userId'>> & {
    updatedAt: Date;
};

/**
 * Client-friendly training plan with string IDs
 */
export interface TrainingPlanClient {
    _id: string;
    userId: string;
    name: string;
    durationWeeks: number;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    /** How the plan was created (manual, ai, import, share, duplicate) */
    creationSource?: PlanCreationSource;
}


