import { ObjectId } from 'mongodb';

/**
 * Report type - either a user-submitted bug or an automatic error
 */
export type ReportType = 'bug' | 'error';

/**
 * Bug category - regular bug or performance issue
 */
export type BugCategory = 'bug' | 'performance';

/**
 * Report status for tracking
 */
export type ReportStatus = 'new' | 'investigating' | 'resolved' | 'closed';

/**
 * Session log entry stored with the report
 */
export interface SessionLogEntry {
    id: string;
    timestamp: string;
    level: 'debug' | 'info' | 'warn' | 'error';
    feature: string;
    message: string;
    meta?: Record<string, unknown>;
    route?: string;
    networkStatus: 'online' | 'offline';
    performanceTime?: number; // performance.now() - time from session start in ms
}

/**
 * Performance entry data for performance bug reports
 */
export interface PerformanceEntryData {
    name: string;
    entryType: string;
    startTime: number;
    duration: number;
    initiatorType?: string;
    transferSize?: number;
    encodedBodySize?: number;
    decodedBodySize?: number;
}

/**
 * User information associated with the report
 */
export interface ReportUserInfo {
    userId?: string;
    username?: string;
    email?: string;
}

/**
 * Browser/device information
 */
export interface ReportBrowserInfo {
    userAgent: string;
    viewport: {
        width: number;
        height: number;
    };
    language: string;
}

/**
 * Represents a bug/error report in the database
 */
export interface ReportDocument {
    _id: ObjectId;
    type: ReportType;
    status: ReportStatus;
    description?: string;
    screenshot?: string; // URL to Vercel Blob (or legacy base64 data)
    sessionLogs: SessionLogEntry[];
    userInfo?: ReportUserInfo;
    browserInfo: ReportBrowserInfo;
    route: string;
    networkStatus: 'online' | 'offline';
    stackTrace?: string;
    errorMessage?: string;
    category?: BugCategory;
    performanceEntries?: PerformanceEntryData[];
    createdAt: Date;
    updatedAt: Date;
}

/**
 * Type for creating a new report
 * Omits the _id field which is generated by MongoDB
 */
export type ReportCreate = Omit<ReportDocument, '_id'>;

/**
 * Type for updating a report
 */
export type ReportUpdate = Partial<Pick<ReportDocument, 'status' | 'updatedAt'>>;

/**
 * Client-friendly report with string IDs
 */
export interface ReportClient {
    _id: string;
    type: ReportType;
    status: ReportStatus;
    description?: string;
    screenshot?: string;
    sessionLogs: SessionLogEntry[];
    userInfo?: ReportUserInfo;
    browserInfo: ReportBrowserInfo;
    route: string;
    networkStatus: 'online' | 'offline';
    stackTrace?: string;
    errorMessage?: string;
    category?: BugCategory;
    performanceEntries?: PerformanceEntryData[];
    createdAt: string;
    updatedAt: string;
}

/**
 * Filters for querying reports
 */
export interface ReportFilters {
    type?: ReportType;
    status?: ReportStatus;
    startDate?: Date;
    endDate?: Date;
}

