#!/usr/bin/env tsx
/**
 * Product Development Agent
 *
 * OPTIONAL phase that transforms vague feature ideas into concrete product specifications.
 * Generates Product Development documents (PDD) that focus on WHAT to build and WHY,
 * not HOW it looks (that's Product Design) or how to implement (that's Tech Design).
 *
 * Creates PRs with design files instead of updating issue body directly.
 *
 * Flow A (New Document):
 *   - Fetches items in "Product Development" status with empty Review Status
 *   - Generates product development document using Claude (read-only mode)
 *   - Creates branch, writes design file, creates PR
 *   - Sends Telegram notification with Approve & Merge buttons
 *   - Sets Review Status to "Waiting for Review"
 *
 * Flow B (Address Feedback):
 *   - Fetches items in "Product Development" with Review Status = "Request Changes"
 *   - Reads admin feedback comments
 *   - Revises product development document based on feedback
 *   - Updates existing design file and PR
 *   - Sets Review Status back to "Waiting for Review"
 *
 * IMPORTANT: This phase is OPTIONAL and only for features, not bugs.
 * Bugs skip directly to Technical Design (or Implementation).
 *
 * Usage:
 *   yarn agent:product-dev                    # Process all pending
 *   yarn agent:product-dev --id <item-id>     # Process specific item
 *   yarn agent:product-dev --dry-run          # Preview without saving
 *   yarn agent:product-dev --stream           # Stream Claude output
 */

import '../../shared/loadEnv';
import {
    // Config
    STATUSES,
    // Prompts
    buildProductDevelopmentPrompt,
    buildProductDevelopmentRevisionPrompt,
    buildProductDevelopmentClarificationPrompt,
    // Output schemas
    PRODUCT_DEVELOPMENT_OUTPUT_FORMAT,
    // CLI & Batch
    createCLI,
    runBatch,
    // Design Agent Processor
    createDesignProcessor,
    // Main factory
    runAgentMain,
} from '../../shared';

// ============================================================
// PROCESSOR
// ============================================================

const processItem = createDesignProcessor({
    workflow: 'product-dev',
    phaseName: 'Product Development',
    designType: 'product-dev',
    agentName: 'product-dev',
    outputFormat: PRODUCT_DEVELOPMENT_OUTPUT_FORMAT,
    outputDesignField: 'document',

    modeLabels: {
        new: 'New Document',
        feedback: 'Address Feedback',
        clarification: 'Clarification',
    },

    progressLabels: {
        new: 'Generating product development document',
        feedback: 'Revising product development document',
        clarification: 'Continuing with clarification',
    },

    skipBugs: true,
    skipBugMessage: 'Skipping bug - Product Development is for features only\nBugs should go directly to Technical Design or Implementation',
    skipBugError: 'Bug reports skip Product Development phase',

    buildNewPrompt: ({ content, allComments }) =>
        buildProductDevelopmentPrompt(content, allComments),

    buildFeedbackPrompt: ({ content, existingDesign, allComments }) =>
        buildProductDevelopmentRevisionPrompt(content, existingDesign, allComments),

    buildClarificationPrompt: ({ content, issueNumber, allComments, clarification }) =>
        buildProductDevelopmentClarificationPrompt(
            { title: content.title, number: issueNumber, body: content.body, labels: content.labels },
            allComments,
            clarification,
        ),

    prTitle: (issueNumber) => `docs: product development for issue #${issueNumber}`,
    prBody: (issueNumber) => `Product Development document for issue #${issueNumber}

This document defines WHAT to build and WHY.

Part of #${issueNumber}

---
*Generated by Product Development Agent*`,
});

// ============================================================
// CLI
// ============================================================

async function main(): Promise<void> {
    const { options } = createCLI({
        name: 'product-development',
        displayName: 'Product Development Agent',
        description: 'Generate Product Development documents for GitHub Project items (OPTIONAL phase for features)',
        extraHeaderLines: ['(OPTIONAL phase for vague feature ideas)'],
    });

    await runBatch(
        {
            agentStatus: STATUSES.productDevelopment,
            agentDisplayName: 'Product Development',
        },
        options,
        processItem,
    );
}

// Run
runAgentMain(main);
