import type { ObjectId } from 'mongodb';

/**
 * Approval status for admin-gated signups.
 * Missing field is treated as 'approved' for backward compatibility
 * with users created before this feature existed.
 *
 * Controlled by `authOverrides.requireAdminApproval` — when enabled,
 * new signups are created with 'pending' and cannot log in until an
 * admin approves them via /admin/approvals.
 */
export type UserApprovalStatus = 'pending' | 'approved' | 'rejected';
export type TwoFactorMethod = 'telegram' | 'email';

/**
 * Represents a user in the system
 * Based on the schema defined in database-schema.md
 */
export interface User {
  _id: ObjectId;
  username: string;     // Indexed, Unique
  email?: string;       // Indexed, Unique (when provided)
  password_hash: string;
  createdAt: Date;
  updatedAt: Date;
  profilePicture?: string;
  notificationsEnabled?: boolean;
  telegramChatId?: string;
  /** Missing = false for backward compatibility */
  twoFactorEnabled?: boolean;
  /** Missing = inferred from legacy config / first available contact */
  twoFactorMethod?: TwoFactorMethod;
  /** Legacy field from initial Telegram-only implementation */
  telegramTwoFactorEnabled?: boolean;
  /** Missing = 'approved' (legacy users) */
  approvalStatus?: UserApprovalStatus;
  /** When admin approved the user (if applicable) */
  approvedAt?: Date;
  /** When admin rejected the user (if applicable) */
  rejectedAt?: Date;
}

/**
 * Type for creating a new user document
 * Omits the _id field which is generated by MongoDB
 */
export type UserCreate = Omit<User, '_id'>;

/**
 * Type for updating a user document
 * All fields are optional except updatedAt
 */
export type UserUpdate = Partial<Omit<User, '_id' | 'createdAt'>> & {
  updatedAt: Date;
};

/**
 * Represents a filter for querying users
 */
export interface UserFilter {
  _id?: ObjectId;
  username?: string | RegExp;
  email?: string | RegExp;
} 
