import {
    getProjectManagementAdapter,
    getProjectConfig,
    addAgentPrefix,
    type ImplementationPhase,
} from '../../shared';
import {
    generateTaskBranchName,
    updateImplementationPhaseArtifact,
} from '../../lib/artifacts';
import { savePhasesToDB, savePhaseStatusToDB } from '../../lib/workflow-db';
import {
    logGitHubAction,
    logFeatureBranch,
    type LogContext,
} from '../../lib/logging';
import { getChangedFiles } from './gitUtils';

interface CreatePRParams {
    adapter: Awaited<ReturnType<typeof getProjectManagementAdapter>>;
    issueNumber: number;
    issueType: string;
    contentTitle: string;
    branchName: string;
    prSummary: string | null;
    comment: string | undefined;
    currentPhase: number | undefined;
    totalPhases: number | undefined;
    currentPhaseDetails: ImplementationPhase | undefined;
    logCtx: LogContext;
}

/**
 * Create a PR for a new implementation, including:
 * - Determining base branch (feature branch for multi-phase, default for single)
 * - Building PR title and body
 * - Creating the PR with review request
 * - Updating artifact comments
 * - Triggering Claude Code review
 * - Posting summary comments
 */
export async function createImplementationPR(params: CreatePRParams): Promise<number> {
    const {
        adapter,
        issueNumber,
        issueType,
        contentTitle,
        branchName,
        prSummary,
        comment,
        currentPhase,
        totalPhases,
        currentPhaseDetails,
        logCtx,
    } = params;

    console.log('  Creating pull request...');
    const repoDefaultBranch = await adapter.getDefaultBranch();

    // Determine base branch for PR:
    // - Multi-phase: target the feature branch
    // - Single-phase: target the default branch (unchanged)
    let prBaseBranch: string;
    if (currentPhase && totalPhases && totalPhases > 1) {
        // Multi-phase: PR targets feature branch
        prBaseBranch = generateTaskBranchName(issueNumber);
        const prTargetMsg = `PR will target feature branch: ${branchName} → ${prBaseBranch}`;
        console.log(`  🌿 ${prTargetMsg}`);
        logFeatureBranch(issueNumber, prTargetMsg);
    } else {
        // Single-phase: PR targets default branch (unchanged)
        prBaseBranch = repoDefaultBranch;
    }

    // Get list of changed files for PR description
    const changedFiles = getChangedFiles(prBaseBranch);
    const filesList = changedFiles.length > 0
        ? changedFiles.map((f) => `- ${f}`).join('\n')
        : 'No files changed';

    // Build commit-message-ready PR title and body
    const prPrefix = issueType === 'bug' ? 'fix' : 'feat';
    const phaseLabel = currentPhase && totalPhases
        ? ` (Phase ${currentPhase}/${totalPhases})`
        : '';
    const prTitle = `${prPrefix}: ${contentTitle}${phaseLabel}`;

    // Phase info header for multi-phase features
    const phaseHeader = currentPhase && totalPhases && currentPhaseDetails
        ? `## Phase ${currentPhase}/${totalPhases}: ${currentPhaseDetails.name}

${currentPhaseDetails.description}

`
        : '';

    let prBodyAboveSeparator: string;

    if (prSummary) {
        prBodyAboveSeparator = `${phaseHeader}${prSummary}

${currentPhase && totalPhases && currentPhase === totalPhases ? `Closes #${issueNumber}` : `Part of #${issueNumber}`}`;
    } else {
        const issueRef = currentPhase && totalPhases && currentPhase === totalPhases
            ? `Closes #${issueNumber}`
            : `Part of #${issueNumber}`;
        prBodyAboveSeparator = `${phaseHeader}See issue #${issueNumber} for details.

${issueRef}`;
    }

    const prBody = `${prBodyAboveSeparator}

---

**Files changed:**
${filesList}

**Test plan:**
- \`yarn checks\` passes ✅
- Manual testing completed ✅

See issue #${issueNumber} for full context, product design, and technical design.

*Generated by Implementation Agent*`;

    // Get admin username from config to request review
    const adminUsername = getProjectConfig().github.owner;

    const pr = await adapter.createPullRequest(
        branchName,
        prBaseBranch,
        prTitle,
        prBody,
        [adminUsername]
    );
    const prNumber = pr.number;
    console.log(`  Created PR #${prNumber}: ${pr.url}`);

    // Log PR targeting for multi-phase
    if (currentPhase && totalPhases && totalPhases > 1) {
        const prCreatedMsg = `Phase ${currentPhase}/${totalPhases} PR #${prNumber} targets feature branch`;
        console.log(`  🌿 ${prCreatedMsg}`);
        logFeatureBranch(issueNumber, prCreatedMsg);
    }

    // Update artifact comment with implementation PR
    try {
        if (currentPhase && totalPhases && currentPhaseDetails) {
            // Multi-phase feature
            await savePhaseStatusToDB(issueNumber, currentPhase, 'in-review', prNumber);
            await updateImplementationPhaseArtifact(
                adapter,
                issueNumber,
                currentPhase,
                totalPhases,
                currentPhaseDetails.name,
                'in-review',
                prNumber
            );
        } else {
            // Single-phase feature - initialize phases array then update status
            await savePhasesToDB(issueNumber, [{ order: 1, name: '' }]);
            await savePhaseStatusToDB(issueNumber, 1, 'in-review', prNumber);
            await updateImplementationPhaseArtifact(
                adapter,
                issueNumber,
                1,
                1,
                '', // No name for single-phase
                'in-review',
                prNumber
            );
        }
        console.log('  Updated artifact comment with PR link');
    } catch (error) {
        // Non-fatal error - PR is still created successfully
        console.warn('  Warning: Failed to update artifact comment:', error instanceof Error ? error.message : String(error));
    }

    // Trigger Claude Code review
    try {
        console.log('  Triggering Claude Code review...');
        const reviewInstructions = `@claude please review this PR

**Review Guidelines:**
- Request changes if there are ANY issues or improvements that provide clear, meaningful value
- Only approve if there are no issues or improvements worth requesting
- Do NOT raise minor/speculative issues: hypothetical edge cases, "add a comment explaining X", optional accessibility on decorative elements, or theoretical concerns without concrete impact
- Only raise issues that are worth the cost of a full revision cycle: actual bugs, logic errors, violations of documented project guidelines, missing state handling, security/performance problems
- All feedback must be within the context of the task/PR scope - do not request changes for unrelated code or out-of-scope improvements`;
        await adapter.addPRComment(prNumber, reviewInstructions);
        console.log('  ✅ Claude Code review triggered');
    } catch (error) {
        // Non-fatal error - PR is still created successfully
        console.warn('  Warning: Failed to trigger Claude Code review:', error instanceof Error ? error.message : String(error));
    }

    // Add status comment on issue (phase-aware)
    const phasePrefix = currentPhase && totalPhases
        ? `**Phase ${currentPhase}/${totalPhases}**: `
        : '';
    const phaseName = currentPhaseDetails?.name ? ` - ${currentPhaseDetails.name}` : '';
    const prLinkComment = addAgentPrefix('implementor', `📋 ${phasePrefix}Opening PR #${prNumber}${phaseName}`);
    await adapter.addIssueComment(issueNumber, prLinkComment);

    // Post summary comment on PR (if available)
    if (comment) {
        const prefixedComment = addAgentPrefix('implementor', comment);
        await adapter.addPRComment(prNumber, prefixedComment);
        console.log('  Summary comment posted on PR');
        logGitHubAction(logCtx, 'comment', 'Posted implementation summary comment on PR');
    }

    return prNumber;
}

interface PostFeedbackParams {
    adapter: Awaited<ReturnType<typeof getProjectManagementAdapter>>;
    issueNumber: number;
    prNumber: number;
    comment: string | undefined;
    currentPhase: number | undefined;
    totalPhases: number | undefined;
    logCtx: LogContext;
}

/**
 * Post feedback response comments on issue and PR, and trigger re-review.
 */
export async function postFeedbackResponse(params: PostFeedbackParams): Promise<void> {
    const {
        adapter,
        issueNumber,
        prNumber,
        comment,
        currentPhase,
        totalPhases,
        logCtx,
    } = params;

    // Add status comment on issue (phase-aware)
    const feedbackPhasePrefix = currentPhase && totalPhases
        ? `**Phase ${currentPhase}/${totalPhases}**: `
        : '';
    const issueStatusComment = addAgentPrefix('implementor', `🔧 ${feedbackPhasePrefix}Addressed feedback on PR #${prNumber} - ready for re-review`);
    await adapter.addIssueComment(issueNumber, issueStatusComment);

    // Use structured output comment if available, otherwise warn
    let feedbackComment: string | undefined;
    if (comment) {
        feedbackComment = comment;
    } else {
        console.warn('  ⚠️ No comment in structured output for feedback response');
    }

    const reReviewInstructions = `

**Review Guidelines:**
- Request changes if there are ANY issues or improvements that provide clear, meaningful value
- Only approve if there are no issues or improvements worth requesting
- Do NOT raise minor/speculative issues: hypothetical edge cases, "add a comment explaining X", optional accessibility on decorative elements, or theoretical concerns without concrete impact
- Only raise issues that are worth the cost of a full revision cycle: actual bugs, logic errors, violations of documented project guidelines, missing state handling, security/performance problems
- All feedback must be within the context of the task/PR scope - do not request changes for unrelated code or out-of-scope improvements`;

    if (feedbackComment) {
        const prefixedComment = addAgentPrefix('implementor', feedbackComment);
        // Add @claude to trigger Claude GitHub App to re-review the fixes
        const commentWithReviewRequest = `${prefixedComment}\n\n@claude please review the changes${reReviewInstructions}`;
        await adapter.addPRComment(prNumber, commentWithReviewRequest);
        console.log('  Feedback response comment posted on PR (with @claude review request)');
        logGitHubAction(logCtx, 'comment', 'Posted feedback response on PR with @claude review request');
    } else {
        // Still trigger @claude review even without detailed comment
        await adapter.addPRComment(prNumber, `@claude please review the changes${reReviewInstructions}`);
        console.log('  Review request posted on PR (no detailed comment available)');
    }
}
