#!/usr/bin/env tsx
/**
 * Product Design Agent
 *
 * Generates Product Design documents for GitHub Project items.
 * Creates PRs with design files instead of updating issue body directly.
 *
 * Flow A (New Design):
 *   - Fetches items in "Product Design" status with empty Review Status
 *   - Generates product design using Claude (read-only mode)
 *   - Creates branch, writes design file, creates PR
 *   - Sends Telegram notification with Approve & Merge buttons
 *   - Sets Review Status to "Waiting for Review"
 *
 * Flow B (Address Feedback):
 *   - Fetches items in "Product Design" with Review Status = "Request Changes"
 *   - Reads admin feedback comments
 *   - Revises product design based on feedback
 *   - Updates existing design file and PR
 *   - Sets Review Status back to "Waiting for Review"
 *
 * Usage:
 *   yarn agent:product-design                    # Process all pending
 *   yarn agent:product-design --id <item-id>     # Process specific item
 *   yarn agent:product-design --dry-run          # Preview without saving
 *   yarn agent:product-design --stream           # Stream Claude output
 */

import '../../shared/loadEnv';
import {
    // Config
    STATUSES,
    // Prompts
    buildProductDesignPrompt,
    buildProductDesignRevisionPrompt,
    buildProductDesignClarificationPrompt,
    // Output schemas
    PRODUCT_DESIGN_OUTPUT_FORMAT,
    // CLI & Batch
    createCLI,
    runBatch,
    // Design Agent Processor
    createDesignProcessor,
} from '../../shared';
import {
    readDesignDoc,
} from '../../lib/design-files';

// ============================================================
// PROCESSOR
// ============================================================

const processItem = createDesignProcessor({
    workflow: 'product-design',
    phaseName: 'Product Design',
    designType: 'product',
    agentName: 'product-design',
    outputFormat: PRODUCT_DESIGN_OUTPUT_FORMAT,
    outputDesignField: 'design',

    modeLabels: {
        new: 'New Design',
        feedback: 'Address Feedback',
        clarification: 'Clarification',
    },

    progressLabels: {
        new: 'Generating product design',
        feedback: 'Revising product design',
        clarification: 'Continuing with clarification',
    },

    skipBugs: true,
    skipBugMessage: `\u23ED\uFE0F  Skipping bug - bugs bypass Product Design phase\n\uD83D\uDCCC Reason: Most bugs don't need product design (they need technical fixes)\n\uD83D\uDCA1 If this bug requires UX/UI redesign, admin can manually move it to Product Design`,
    skipBugError: 'Bug reports skip Product Design by default',

    buildNewPrompt: ({ content, additionalContext, allComments }) =>
        buildProductDesignPrompt(content, additionalContext, allComments),

    buildFeedbackPrompt: ({ content, existingDesign, allComments }) =>
        buildProductDesignRevisionPrompt(content, existingDesign, allComments),

    buildClarificationPrompt: ({ content, issueNumber, allComments, clarification }) =>
        buildProductDesignClarificationPrompt(
            { title: content.title, number: issueNumber, body: content.body, labels: content.labels },
            allComments,
            clarification,
        ),

    loadAdditionalContext: async ({ issueNumber }) => {
        // Check for Product Development Document (PDD) if this feature went through that phase
        const productDevelopmentDoc = readDesignDoc(issueNumber, 'product-dev');
        return productDevelopmentDoc
            ? { context: productDevelopmentDoc, label: 'Found Product Development Document (PDD) - will use as context' }
            : { context: null };
    },

    prTitle: (issueNumber) => `docs: product design for issue #${issueNumber}`,
    prBody: (issueNumber) => `Design document for issue #${issueNumber}

Part of #${issueNumber}

---
*Generated by Product Design Agent*`,
});

// ============================================================
// CLI
// ============================================================

async function main(): Promise<void> {
    const { options } = createCLI({
        name: 'product-design',
        displayName: 'Product Design Agent',
        description: 'Generate Product Design documents for GitHub Project items',
    });

    await runBatch(
        {
            agentStatus: STATUSES.productDesign,
            agentDisplayName: 'Product Design',
        },
        options,
        processItem,
    );
}

// Run
main()
    .then(() => {
        process.exit(0);
    })
    .catch((error) => {
        console.error('Fatal error:', error);
        process.exit(1);
    });
